# provision.yml

- name: Provision base packages for machine
  hosts: "all"
  become: true
  
  tasks:
    - name: get hostname
      shell: hostname
      register: hostname

    - name: apt install basics
      apt: 
        pkg:
          - debian-goodies
          - needrestart
          - debsecan
          - debsums
          - curl 
          - git 
          - zsh
          - nano
          - bash-completion
          - nmap
          - apt-transport-https
          - socat

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

- name: Provision roles for machine
  hosts: "all"
  become: true
  
  roles:
    - name: Install docker
      role: "nickjj.docker"
      tags: ["docker"]
      vars:
        docker__edition: "ce"
        docker__channel: ["stable"]
        docker__version: "18.09.3"
        #docker__version: "18.06.1"

    - name: Install oh-my-zsh
      role: gantsign.oh-my-zsh
      users:
        - username: vagrant
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git        

- name: Install dotfiles 
  hosts: "all"
  become: true
  
  tasks:            
    - name: Clone dotfiles
      git:
        repo: 'https://github.com/chrisguest75/default_dotfiles.git'
        dest: /home/vagrant/Code/default_dotfiles
      become_user: vagrant

    - name: Install dotfiles
      shell: /home/vagrant/Code/default_dotfiles/install.sh 
      become_user: vagrant

    - name: Install kubernetes snaps with option --classic
      snap:
        name: 
          - kubeadm
          - kubelet
          - kubectl
        classic: yes

    # - name: Pull images 
    #   shell: |
    #     kubeadm config images pull
    #   args:
    #     executable: /usr/bin/zsh
    #   become_user: vagrant

    